---
title: "Dice experiment"
output:
  pdf_document:
    includes:
      in_header: preamble.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\thispagestyle{fancy}

## Instructions

* Obtain a 6-sided die. ("Die" is the singular of "dice".)
* Repeat 3 times:
    - Roll the die 10 times, recording each roll.
    - Determine the total and mean.
    - Make a frequency table.
    - Make a (stacked) dot plot.
* Tell the professor your 3 means. All of the class's means will be recorded on the tally table.
* Copy the class's means onto your own tally table.
* Make a histogram of the class's means.

## Homework

* On the last page, summarize in your own words what we did and what the results were. Also, on the last page, answer the following questions.
    - How many times did you roll a 1?
    - How many times did anyone in the class get a mean of 1?
    - Why is it easier to roll a 1 than to get a mean of 1?
    - If you rolled the die 1000 times and made a dot plot, what shape would you expect? (bell, uniform, bimodal, left-skewed, or right-skewed?)
    - What shape did the histogram of the class's means have?
