---
header-includes:
   - \usepackage{multicol}
output:
  pdf_document: default
  html_document: default
---

```{r data generation, echo = FALSE, results = "hide"}
types = c("1","2","3","4")
while(T){
  mus = sample(600:900/10,4)
  sigs = sample(40:150/10,4)
  ps = round(runif(4,0.02,0.98),4)
  zs = round(qnorm(ps),2)
  xs = signif(mus+zs*sigs,4)
  zs = round((xs-mus)/sigs,2)
  ps = round(pnorm(zs),4)
  if(sort(zs)==sort(unique(zs)) & sum(zs<0)>1){
    break
  }
}
```

Question
========

Yasmine took 4 exams for her statistics class. Each exam yields normally distributed scores. Yasmine's scores and the exams' means and standard deviations are shown below.

\begin{center}
\begin{tabular}{|c|c|c|c|}\hline
Exam & Yasmine's score & Mean scores & SD of scores \\ \hline
1 & `r xs[1]`  & `r mus[1]` & `r sigs[1]` \\
2 & `r xs[2]`  & `r mus[2]` & `r sigs[2]` \\
3 & `r xs[3]`  & `r mus[3]` & `r sigs[3]` \\
4 & `r xs[4]`  & `r mus[4]` & `r sigs[4]` \\ \hline
\end{tabular}
\end{center}

On which exam did Yasmine perform worst compared to other people?

Solution
========

We compare the $z$-scores. The smallest $z$-score corresponds to the worst score.

\begin{center}
\renewcommand*{\arraystretch}{1.3}
\begin{tabular}{|c|c|c|}\hline
Exam & formula &  $z$-score \\ \hline
1 & $z=\frac{`r xs[1]`-`r mus[1]`}{`r sigs[1]`}$ &`r zs[1]` \\
2 & $z=\frac{`r xs[2]`-`r mus[2]`}{`r sigs[2]`}$ &`r zs[2]` \\
3 & $z=\frac{`r xs[3]`-`r mus[3]`}{`r sigs[3]`}$ &`r zs[3]` \\
4 & $z=\frac{`r xs[4]`-`r mus[4]`}{`r sigs[4]`}$ &`r zs[4]` \\ \hline
\end{tabular}
\end{center}

Thus, Yasmine did worst on exam $`r types[zs==min(zs)]`$.

Meta-information
============
extype: string
exsolution: yo
exname: UZ
extol: 0.01
