---
title: "Syllabus (short version)"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Professor

- Chad Worley
- ceworley@bhcc.edu

## Class

- Mat-181 Introductory Statistics
- Tuesdays and Thursdays @ 8:30 AM - 9:45 AM
- Room D209

## Calculator

* I recommend TI-30XS-Multiview, TI-30XIIS, TI-84, or TI-89.
* If you have a smart phone, you can use Geogebra Scientific Calculator.
    - During exams you will use airplane mode (and exam mode).

## Textbook

* OpenIntro Stats
    * https://www.openintro.org/book/os/
    * Free to download (Available on our moodle)
    * About $20 for a paper copy

## Grade breakdown

* 30% Exams
* 20% Final
* 20% Homework/Quizzes
* 20% Project
* 10% Attendance/participation

## Schedule

* Tuesdays and Thursdays @ 8:30 AM
* Jan 21st until May 14th (If you plan to leave before May 14th, please drop the course.)
* Holidays:
    - March 17 (Spring Break)
    - March 19 (Spring Break)
    - April 21 (Monday Schedule)
* Exams:
    - Feb 13
    - Mar 12
    - Apr 16
    - May 14
    
## Project

* You will do original research.
    - Collect data (your own original data)
    - Analyze the data with at least a **confidence interval** or **hypothesis test**
    - Write a paper
    - Make and present a presentation
* Dates:
    - Mar 12: Proposal 
    - May 5, May 7: Presentations
    - May 14: Paper is due

## Tutoring

* Please go to TASC in room Room E174 regularly to get assistance from tutors. The one-on-one attention is very helpful.

## Homework

* I am hoping to have homework on Moodle this semester, but there may also be pen-and-paper assignments (and problems given from the textbook.)
* We may also use Rstudio 

## Code of conduct

* All	students	are	expected	to	adhere	to	the	honor	code	regarding	course	assignments	and	exams.		This	includes	completing	assignments	without	unauthorized	aid	when	instructed.		Any	student	suspected	of	cheating	on	an	assignment	or	an	exam	will	not	pass	that	assignment	or	exam.

