
```{r data generation, echo = FALSE, results = "hide"}
while(T){
    n = sample(4:7,1)
    x = sort(sample(1:30,n))
    l = sort(round(runif(n-1,0,1),2))
    breaks = c(0,l,1)
    p = round(breaks[2:(n+1)]-breaks[1:n],2)
    mu = sum(p*x)
    sig = sqrt(sum(p*(x-mu)^2))
    # the following requirements add considerable time...
    if(sum(p)==1 & sum(p>0.05)==n & as.integer(mu)==mu & as.integer(sig*100)==sig*100){
        break
    }
}

s = ''
for(i in 1:n){
    s = paste(s,'|',x[i],'|',p[i],'|\n')
}

c3 = x*p
c4 = x-mu
c5 = (x-mu)^2
c6 = p*(x-mu)^2

s2 = ''
for(i in 1:n){
    s2 = paste(s2,'|',x[i],'|',p[i],'|',c3[i],'|',c4[i],'|',c5[i],'|',c6[i],'|')
    if(i < n){
        s2 = paste(s2,'\n')
    }
}

exact = sample(1:n,1)
xex = x[exact]
two = sort(sample(1:n,2))
ptwo = sum(p[two])
if(n==3){
  atlm = 2
} else {
  atlm = sample(2:(n-1),size=1)
}
xatlm = x[atlm]
atl = sample(c(T,F),1)
if(atl){
  word = "least"
  patlm = sum(p[atlm:n])
  sym = "\\ge"
} else {
  word = "most"
  patlm = sum(p[1:atlm])
  sym = "\\le"
}

```

Question
========

A spinner has the probability distribution shown below.

| $x$ | $\text{Pr}(x)$ |
|:---:|:---:|
`r s`

Answerlist
--------

* What is the probability of spinning `r xex`? In other words, what is $\text{Pr}(X=`r xex`)$?
* What is the probability of spinning `r x[two[1]]` or `r x[two[2]]`? In other words, what is $\text{Pr}(X=`r x[two[1]]` ~\text{ or }~ X=`r x[two[2]]`)$?
* If spinning twice, what is the probability of first spinning `r x[two[1]]` and then spinning `r x[two[2]]`? In other words, what is $\text{Pr}(X_1=`r x[two[1]]` ~\text{ and }~ X_2=`r x[two[2]]`)$?
* What is the probability of spinning at `r word` `r xatlm`? In other words, what is $\text{Pr}(X`r sym` `r xatlm`)$?
* Determine the mean of the probability distribution by using $\mu = \sum x\cdot \text{Pr}(x)$.
* Determine the standard deviation of the probability distribution by using $\sigma = \sqrt{\sum (x-\mu)^2 \cdot \text{Pr}(x)}$.


Solution
========

Make a table (for parts mean and standard deviation).

```{r table, echo=F}
s3 = '\\begin{center}\n\\begin{tabular}{|c|c|c|c|c|c|} \\hline\n'
s3 = paste(s3, "$x$ & $\\text{Pr}(x)$ & $x\\cdot\\text{Pr}(x)$ & $x-\\mu$ & $(x-\\mu)^2$ & $(x-\\mu)^2 \\cdot \\text{Pr}(x)$ \\\\ \\hline\n")
for(i in 1:n){
    s3 = paste(s3,x[i],'&',p[i],'&',c3[i],'&',c4[i],'&',c5[i],'&',c6[i],'\\\\')
    if(i < n){
        s3 = paste(s3,'\n')
    }
}
s3 = paste(s3, '\\hline\n')
s3 = paste(s3, "& & $\\sum x \\cdot \\text{Pr}(x)=",mu,"$& & & $\\sigma^2 =",sum(c6),"$ \\\\ \\hline\n")
s3 = paste(s3, "& & $\\mu=",mu,"$& & & $\\sigma =",sig,"$ \\\\ \\hline\n")
s3 = paste(s3,"\\end{tabular}\n\\end{center}",sep="")
```


| $x$ | $\text{Pr}(x)$ | $x\cdot\text{Pr}(x)$ | $x-\mu$ | $(x-\mu)^2$ | $(x-\mu)^2 \cdot \text{Pr}(x)$|
|:---:|:---:|:---:|:---:|:---:|:---:|
`r s2`
|=========|=========|=========|=========|=========|=========|
|     |     | $\sum x \cdot \text{Pr}(x) = `r mu`$ |   |   | $\sigma^2 = `r sum(c6)`$   |
|     |     | $\mu = `r mu`$ |   |   | $\sigma = `r sig`$   |

<!-- `r s3` -->

Answerlist
--------

* `r p[exact]`
* $`r p[two[1]]` + `r p[two[2]]`$ = **`r ptwo`**
* $`r p[two[1]]` \times `r p[two[2]]`$ = **`r p[two[1]]*p[two[2]]`**
* `r patlm`
* $\mu = `r mu`$
* $\sigma = `r sig`$


Meta-information
============
extype: cloze
exsolution: `r p[exact]`|`r ptwo`|`r p[two[1]]*p[two[2]]`|`r patlm`|`r mu`|`r sig`|
exclozetype: num|num|num|num|num|num
exname: probdist
extol: 0.01
