
```{r data generation, echo = FALSE, results = "hide"}
library(exams)
options(scipen=100)
types = c("A","B","C","D")
fruit = c("apple","orange","banana","mango","plum","grapefruit","kiwi","lemon","papaya","apricot","persimmon","watermelon","pineapple","coconut")
mass = c(180,180,180,250,90,240,80,100,450,50,170,9000,2000,700)
is = sample(1:length(mass),4)
while(T){
  is = sample(1:length(mass),4)
  f = fruit[is]
  fs = paste(f,"s",sep="")
  mus = round(mass[is]*runif(4,0.7,1.3))
  sigs = round(mus/runif(4,6,20))
  ps = runif(4,0.02,0.98)
  zs = round(qnorm(ps),2)
  xs = signif(mus+zs*sigs,4)
  zs = round((xs-mus)/sigs,2)
  ps = round(pnorm(zs),4)
  if(sum(zs>0)>=1 & sum(zs<0)>=1 & length(unique(abs(zs)))==4 & min(c(dist(abs(zs),method = "manhattan"))) > 0.1){
    break
  }
}

scs1 = mchoice2string(zs==max(zs))
scs2 = mchoice2string(zs==min(zs))
scs3 = mchoice2string(abs(zs)==min(abs(zs)))
scs4 = mchoice2string(abs(zs)==max(abs(zs)))
```

Question
========

A farm produces 4 types of fruit: `r fs[1]`, `r fs[2]`, `r fs[3]`, and `r fs[4]`. The fruits' masses follow normal distributions, with parameters dependent on the type of fruit.

| Type of fruit _ | _ Mean mass (g) _ | _ Standard deviation of mass (g) _ |
|:---:|:---:|:---:|
|`r fs[1]` | `r mus[1]` | `r sigs[1]` | 
|`r fs[2]` | `r mus[2]` | `r sigs[2]` |
|`r fs[3]` | `r mus[3]` | `r sigs[3]` |
|`r fs[4]` | `r mus[4]` | `r sigs[4]` |


One specimen of each type is weighed. The results are shown below.

| specimen type _ | _ Mass of specimen (g) |
|:---:|:---:|
|`r f[1]` | `r xs[1]` |
|`r f[2]` | `r xs[2]` |
|`r f[3]` | `r xs[3]` |
|`r f[4]` | `r xs[4]` |


Answerlist
--------
* Calculate a $z$ score for the `r f[1]` specimen. (Round to the nearest hundredth.)
* What percent of `r fs[1]` have less mass than the `r f[1]` specimen?
* Calculate a $z$ score for the `r f[2]` specimen. (Round to the nearest hundredth.)
* What percent of `r fs[2]` have less mass than the `r f[2]` specimen?
* Calculate a $z$ score for the `r f[3]` specimen. (Round to the nearest hundredth.)
* What percent of `r fs[3]` have less mass than the `r f[3]` specimen?
* Calculate a $z$ score for the `r f[4]` specimen. (Round to the nearest hundredth.)
* What percent of `r fs[4]` have less mass than the `r f[4]` specimen?
* The `r f[1]` specimen is most unusually large.
* The `r f[2]` specimen is most unusually large.
* The `r f[3]` specimen is most unusually large.
* The `r f[4]` specimen is most unusually large.
* The `r f[1]` specimen is most unusually small.
* The `r f[2]` specimen is most unusually small.
* The `r f[3]` specimen is most unusually small.
* The `r f[4]` specimen is most unusually small.
* The `r f[1]` specimen is most typically sized.
* The `r f[2]` specimen is most typically sized.
* The `r f[3]` specimen is most typically sized.
* The `r f[4]` specimen is most typically sized.
* The `r f[1]` specimen is most unusually sized.
* The `r f[2]` specimen is most unusually sized.
* The `r f[3]` specimen is most unusually sized.
* The `r f[4]` specimen is most unusually sized.

Solution
========

Answerlist
--------
* We use the formula for calculating the `r f[1]` specimen's $z$ score.
$$z = \frac{`r xs[1]`-`r mus[1]`}{`r sigs[1]`} = `r zs[1]` $$
* Use the $z$ table to find the percentile rank.
$$P(Z<`r zs[1]`) = `r ps[1]` $$
* We use the formula for calculating the `r f[2]` specimen's $z$ score.
$$z = \frac{`r xs[2]`-`r mus[2]`}{`r sigs[2]`} = `r zs[2]` $$
* Use the $z$ table to find the percentile rank.
$$P(Z<`r zs[2]`) = `r ps[2]` $$
* We use the formula for calculating the `r f[3]` specimen's $z$ score.
$$z = \frac{`r xs[3]`-`r mus[3]`}{`r sigs[3]`} = `r zs[3]` $$
* Use the $z$ table to find the percentile rank.
$$P(Z<`r zs[3]`) = `r ps[3]` $$
* We use the formula for calculating the `r f[4]` specimen's $z$ score.
$$z = \frac{`r xs[4]`-`r mus[4]`}{`r sigs[4]`} = `r zs[4]` $$
* Use the $z$ table to find the percentile rank.
$$P(Z<`r zs[4]`) = `r ps[4]` $$
* We determine the maximum $z$ score is $`r max(zs)`$, which belongs to the `r f[zs==max(zs)]`.
* .
* .
* .
* We determine the minimum $z$ score is $`r min(zs)`$, which belongs to the `r f[zs==min(zs)]`.
* .
* .
* .
* We determine the minimum absolute $z$ score is $`r min(abs(zs))`$, which belongs to the `r f[abs(zs)==min(abs(zs))]`.
* .
* .
* .
* We determine the maximum absolute $z$ score is $`r max(abs(zs))`$, which belongs to the `r f[abs(zs)==max(abs(zs))]`.
* .
* .
* .


Meta-information
============
extype: cloze
exclozetype: num|num|num|num|num|num|num|num|schoice|schoice|schoice|schoice
exsolution: `r zs[1]`|`r ps[1]`|`r zs[2]`|`r ps[2]`|`r zs[3]`|`r ps[3]`|`r zs[4]`|`r ps[4]`|`r scs1`|`r scs2`|`r scs3`|`r scs4`
exname: compare zs
extol: 0.011|0.004|0.011|0.004|0.011|0.004|0.011|0.004|0|0|0|0
